name: nexus_goll_final
description: "Nexus MK"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  app_settings: ^6.1.1
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  device_info_plus: ^11.5.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.3.0
  qr_flutter: ^4.1.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  lottie: ^3.1.0
  local_auth: ^2.3.0
  permission_handler: ^12.0.0+1
  confetti: ^0.8.0
  image_picker: ^0.8.7+5
  flutter_image_compress: ^1.1.0
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  vibration: ^2.0.0
  safe_device: ^1.3.8  # Detecci√≥n de seguridad: root, GPS falso, emulador
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.3
  flutter_spinkit: ^5.2.2
  modal_bottom_sheet: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  animated_notch_bottom_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_nexus.png
    - assets/logo_nexusa.png
    - assets/logo_nexuss.png
    - assets/lottie/success.json
    - assets/lottie/error.json
    - assets/lottie/Fireworks.json
    - assets/lottie/Confetti.json
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
